import mongoose from 'mongoose';

/**
 * Project Schema
 * Stores comprehensive engineering project showcases, classification tags,
 * runtime scripts, environment configurations, and engagement metrics.
 */
const projectSchema = new mongoose.Schema(
  {
    student: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Student owner ID is required'],
      index: true,
    },
    title: {
      type: String,
      required: [true, 'Project title is required'],
      trim: true,
    },
    tagline: {
      type: String,
      trim: true,
      default: '',
    },
    category: {
      type: String,
      required: [true, 'Domain category is required'],
      trim: true,
    },
    subcategory: {
      type: String,
      trim: true,
      default: '',
    },
    subdomain: {
      type: String,
      trim: true,
      default: '',
    },
    majorStack: {
      type: String,
      trim: true,
      default: '',
    },
    thumbnailUrl: {
      type: String,
      default: '',
    },
    description: {
      type: String,
      default: '',
    },
    tags: [{ type: String, trim: true }],
    installCmd: {
      type: String,
      default: '',
    },
    runCommand: {
      type: String,
      default: '',
    },
    testCmd: {
      type: String,
      default: '',
    },
    envVariables: [
      {
        key: { type: String, trim: true },
        value: { type: String },
      },
    ],
    envNotes: {
      type: String,
      default: '',
    },
    githubUrl: {
      type: String,
      trim: true,
      default: '',
    },
    liveUrl: {
      type: String,
      trim: true,
      default: '',
    },
    demoVideoUrl: {
      type: String,
      trim: true,
      default: '',
    },
    executableFile: {
      name: { type: String, default: '' },
      url: { type: String, default: '' },
      size: { type: Number, default: 0 },
      uploadedAt: { type: Date, default: null },
    },
    status: {
      type: String,
      enum: ['Published', 'Draft', 'Build Verified', 'Audit Approved'],
      default: 'Published',
    },
    grade: {
      type: String,
      default: null, // e.g. 'Grade A+', 'Grade A' generated by AI
    },
    score: {
      type: Number,
      default: null, // AI will generate this score (0 - 100)
      min: 0,
      max: 100,
    },
    aiEvaluation: {
      status: {
        type: String,
        enum: ['Pending', 'Evaluating', 'Completed', 'Failed'],
        default: 'Pending',
      },
      grade: { type: String, default: null },
      score: { type: Number, default: null },
      evaluatedAt: { type: Date, default: null },
      summary: { type: String, default: '' },
      checks: [
        {
          name: { type: String },
          category: { type: String },
          status: { type: String },
          detail: { type: String },
        },
      ],
    },
    views: {
      type: Number,
      default: 0,
    },
    bookmarks: {
      type: Number,
      default: 0,
    },
  },
  {
    timestamps: true,
  }
);

// Index for high-performance category & text searches
projectSchema.index({ category: 1, subcategory: 1, subdomain: 1 });
projectSchema.index({ title: 'text', description: 'text', tags: 'text' });

const Project = mongoose.model('Project', projectSchema);
export default Project;
